### ISSUE TITLE
Comments for dc25/myBlog

### ISSUE THREAD

**Issue by dc25** [dc25/myBlog-comments#1]
Comments for blog post : [Using github comments in a Jekyll blog](http://dc25.github.io/myBlog/2017/06/24/using-github-comments-in-a-jekyll-blog.html)

**Comment by dc25** [comment]
this is a comment

**Comment by dc25** [comment]
this is another comment

**Comment by dc25** [comment]
This is a comment with some markdown...

- Listy
- Listo

1. Jumble
2. Sale

**Boldit** or _Italicit_ or ~~strikeit~~
# header

```c++
// c++ syntax
int x = 3;
```

**Comment by berot3** [comment]
I like! 🙂👍

**Comment by funkypenguin** [comment]
Nice! ;)

**Comment by jasonLiu001** [comment]
Very nice! A wonderful solution for Jekyll site. Very helpful.

**Comment by mariotalavera** [comment]
this is a test. good job

**Comment by dc25** [comment]
Testing on new page.

**Comment by cinhtau** [comment]
Great solution!

**Comment by pawelmarcinkowski-gh** [comment]
Nice

**Comment by moustaphacheikh** [comment]
this is fun

**Comment by ninest** [comment]
Interesting solution!

**Comment by ravshanof** [comment]
Testing

**Comment by dc25** [comment]
Testing 
![airplane](https://user-images.githubusercontent.com/1620/43170803-d9637b90-8f5b-11e8-8e1b-a5569b67d1a0.gif)

**Comment by ghost** [comment]
Testing ... Thanks for the solution.

**Comment by dc25** [comment]
more testing
```haskell
--haskell syntax
main :: IO ()
main = do
  print "Hello World"
  print "Hello Again"
```
```c++
// c++ syntax
int x = 3;

```

**Comment by polishman** [comment]
fadfadfadsfds

**Comment by davidobrien1985** [comment]
Hi, did you ever manage to "migrate" the disqus comments over to github or did you just not bother with them?

**Comment by dc25** [comment]
Hi @davidobrien1985,  

I didn't bother.  Given that I could keep using disqus comments for old posts and switch to using github comments for new posts, it didn't seem that important.

- Dave

**Comment by davidobrien1985** [comment]
@dc25 that's what I ended up doing on my blog now as well. 
Thanks for your article. Without even advertising the fact that I was switching to github issues as comments people automatically started doing it.
Great job!

**Comment by ninest** [comment]
Is it possible to allow users to comment **without** creating a GitHub account?

**Comment by dc25** [comment]
@themindstorm,

> Is it possible to allow users to comment **without** creating a GitHub account?

I can't think of a way, not as a variant of this technique.

**Comment by dvijayak** [comment]
> @themindstorm,
> 
> > Is it possible to allow users to comment **without** creating a GitHub account?
> 
> I can't think of a way, not as a variant of this technique.

I wonder if a comment form can be implemented which will post comments using the github account of the article author (in this case, @dc25). The form will have a field for a special linked identifier (github account, email address, etc.) which would serve as a way to uniquely identify the author of the comment. This "metadata" could be rendered as desired to make it clear as to who the author of the comment is.

This would be one (inelegant) way to accomplish the goal of comments from users regardless of whether they own a github account or not.

**Comment by laegsgaardTroels** [comment]
Testing

**Comment by jmichalak9** [comment]
It's absolutely brilliant!

**Comment by ChangJoo-Park** [comment]
awesome

**Comment by Mrc0113** [comment]
awesome! thanks!

**Comment by shadlyd15** [comment]
Cleaver Idea!

**Comment by jangid** [comment]
Instead of taking to comments page, you could use Github APIs to comment directly from the post page. https://developer.github.com/v3/issues/comments/

**Comment by wini3d** [comment]
Test comment :+1:

**Comment by resthyphen** [comment]
> Test comment
agree

**Comment by awootton** [comment]
Hello From Atw

**Comment by icefelt** [comment]
Interesting and thanks for posting.

**Comment by junhan-z** [comment]
OK...

**Comment by marcoroda** [comment]
Thanks!!

**Comment by oldgit** [comment]
Thanks - I did have google+ comments but google+ is no more, so this is great.

**Comment by bennihtm** [comment]
### 

> [`_****_`](

- 

- [x] 1. url

)

**Comment by dbereghici** [comment]
test

**Comment by marcoct** [comment]
does it still work

**Comment by dc25** [comment]
It still works.    Every now and then I rebase the reference implementation ( see the blog post for details ) to the latest minima and rebuild with the current jekyll to make sure.     So far there have been no problems.    I went through this process today (2020-08-30) and a few months ago ( 2020-05-29 ).   After doing this exercise, I always re-publish the reference implementation on github.

**Comment by ghost** [comment]
Test

**Comment by vishnuharidas** [comment]
It's funny that people are still testing the comments.

```kotlin
main(){
    println("Ok working")
}
```

**Comment by mediocreone** [comment]
Aloha!

- [x] Complete test
- [ ] Incomplete test

**Comment by 5arthak01** [comment]
testing

**Comment by Lzy17** [comment]
$$x_{1,2} = \frac{-b \pm \sqrt{b^2-4ac}}{2b}.

**Comment by Lzy17** [comment]
![equation](http://www.sciweavers.org/tex2img.php?eq=1%2Bsin%28mc%5E2%29&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=)

**Comment by Lzy17** [comment]
h<sub>&theta;</sub>(x) = &theta;<sub>o</sub> x + &theta;<sub>1</sub>x

**Comment by Lzy17** [comment]
$$ \nabla_\boldsymbol{x} J(\boldsymbol{x}) $$

**Comment by prasadhonrao** [comment]
testing comment

**Comment by erinvasquez** [comment]
Wow how cool is this

**Comment by manifestosanvincenzo** [comment]
cooomento

**Comment by isurunuwanthilaka** [comment]
Nice solution!

**Comment by jays1ngh** [comment]
Testing

**Comment by jays1ngh** [comment]
> Testing 

How does quote reply work?

**Comment by morgosus** [comment]
Just wanna see what this will look like.

**Comment by sandrods** [comment]
does this reaaly work?

**Comment by yuxyym** [comment]
why is it sorted from oldest to newest

**Comment by jays1ngh** [comment]
No clue

On 31 Oct 2021, at 3:38 pm, ***@***.*** wrote:

﻿

why is it sorted from oldest to newest

**Comment by dc25** [comment]
The comments are sorted from oldest to newest because that's how they were sorted in [the original reference implementation](http://donw.io/post/github-comments/).   I started with that and never changed it.
###
It seems like the right choice.  Most platforms that I have seen that allow comments display them from oldest to newest.    I think that's what most people are used to.
###
That said, anyone who wants to use this system with sorting from newest to oldest can edit the following lines in [github-comments.js](https://github.com/dc25/minimaWithGithubComments/blob/master/js/github-comments.js) :
###
```javascript
// choose one of the next two lines to determine display order (newest or oldest first).
const commentsHtml = comments.join('');                // oldest first
// const commentsHtml = comments.reverse().join('');   // newest first
```

**Comment by flynnsharwood** [comment]
comment

**Comment by kabir** [comment]
Test

**Comment by xwenliang** [comment]
work like a charm!

**Comment by everycoinprice** [comment]
Great work

**Comment by Aftorres02** [comment]
wow

**Comment by Aftorres02** [comment]
wow

**Comment by amc1981** [comment]
Hey there!

**Comment by dstocking** [comment]
Love this as a solution!

**Comment by SunKing2** [comment]
Very cool.   I gutta try this!

**Comment by anasvemmully** [comment]
great, i was looking for how to do comments in jekyll ☺

**Comment by pspowell** [comment]
This is a great idea

**Comment by marcospgp** [comment]
Testing!

**Comment by heironimus** [comment]
Testing in 2024

**Comment by ilgaur** [comment]
Testing!

**Comment by cartovue** [comment]
Appears to still work in late 2025, very impressive! (with edits, no less)
